version: '3.9'

services:
  app:
    build: .
    image: best-track-web/node:14.17.6
    container_name: best-track-web-app
    entrypoint: ./.docker/entrypoint.sh  
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000